// Generated by pnpm capture:marketing. Do not edit.
export const MARKETING_IMAGES = {
  "ai-preview": {
    width: 600,
    height: 374,
  },
  ask: {
    width: 1440,
    height: 900,
  },
  "loop-capture": {
    width: 720,
    height: 46,
  },
  "loop-execute": {
    width: 720,
    height: 214,
  },
  "loop-organize": {
    width: 960,
    height: 211,
  },
  "loop-review": {
    width: 365,
    height: 210,
  },
  notes: {
    width: 1440,
    height: 900,
  },
  projects: {
    width: 1440,
    height: 900,
  },
  tasks: {
    width: 1440,
    height: 900,
  },
  today: {
    width: 1440,
    height: 900,
  },
} as const;

export type MarketingImage = keyof typeof MARKETING_IMAGES;
