// Generates both color themes from three inputs and writes them into the marked blocks of
// src/styles/globals.css and DESIGN.md (feature 07 §5.1). Run: pnpm theme:generate
// Edit the inputs in src/lib/theme/generate.ts, never the generated hexes.
//
// Refuses to write anything if a text pair falls under 4.5:1 or a boundary under 3:1.
import { readFile, writeFile } from "node:fs/promises";
import { format, resolveConfig } from "prettier";
import {
  DEFAULT_INPUTS,
  TAG_COLORS,
  generateTheme,
  type Mode,
  type Palette,
} from "../src/lib/theme/generate";

const check = process.argv.includes("--check");
const theme = generateTheme(DEFAULT_INPUTS);

if (theme.failures.length > 0) {
  console.error("Contrast check failed; nothing written:");
  for (const f of theme.failures) {
    console.error(
      `  ${f.mode}: ${f.fg} on ${f.bg} = ${f.ratio.toFixed(2)} (needs ${f.min}, ${f.why})`,
    );
  }
  process.exit(1);
}

function cssBlock(mode: Mode, palette: Palette, effects: Record<string, string>): string {
  const lines = Object.entries(palette).map(([k, v]) => `  --${k}: ${v};`);
  lines.push(...Object.entries(effects).map(([k, v]) => `  --${k}: ${v};`));
  if (mode === "light")
    lines.push(...Object.entries(TAG_COLORS).map(([k, v]) => `  --tag-${k}: ${v};`));
  return lines.join("\n");
}

function replaceBetween(text: string, start: string, end: string, body: string, file: string) {
  const a = text.indexOf(start);
  const b = text.indexOf(end);
  if (a === -1 || b === -1 || b < a)
    throw new Error(`Markers ${start} / ${end} not found in ${file}`);
  return `${text.slice(0, a + start.length)}\n${body}\n${text.slice(b)}`;
}

const cssPath = "src/styles/globals.css";
let css = await readFile(cssPath, "utf8");
css = replaceBetween(
  css,
  "/* theme:light:start (generated by pnpm theme:generate; do not edit) */",
  "/* theme:light:end */",
  cssBlock("light", theme.palettes.light, theme.effects.light),
  cssPath,
);
css = replaceBetween(
  css,
  "/* theme:dark:start (generated by pnpm theme:generate; do not edit) */",
  "/* theme:dark:end */",
  cssBlock("dark", theme.palettes.dark, theme.effects.dark),
  cssPath,
);

// DESIGN.md keeps the named tokens it documents (not the shadcn aliases).
const DOC_TOKENS = [
  "sidebar",
  "background",
  "card",
  "overlay",
  "muted",
  "hover",
  "accent-float",
  "border",
  "border-strong",
  "input",
  "foreground",
  "muted-foreground",
  "primary",
  "primary-strong",
  "primary-subtle",
  "primary-foreground",
  "destructive",
  "destructive-subtle",
  "warning",
  "warning-subtle",
  "success",
  "ai-surface",
  "ai-border",
  "landing-wash",
];
const yaml: string[] = [];
for (const mode of ["light", "dark"] as const) {
  const p = theme.palettes[mode];
  yaml.push(`  # ${mode === "light" ? "Light" : "Dark"}`);
  for (const token of DOC_TOKENS) {
    if (mode === "light" && token === "overlay") continue; // light overlay is the card
    if (mode === "light" && token === "accent-float") continue; // light float hover is hover
    const name = mode === "light" ? token : `dark-${token}`;
    yaml.push(`  ${name}: "${p[token]!.toUpperCase()}"`);
  }
}
yaml.push("  # Project and tag markers (named product colors; not generated)");
for (const [k, v] of Object.entries(TAG_COLORS)) yaml.push(`  tag-${k}: "${v.toUpperCase()}"`);

const docPath = "DESIGN.md";
let doc = await readFile(docPath, "utf8");
doc = replaceBetween(
  doc,
  "  # theme:start (generated by pnpm theme:generate; do not edit)",
  "  # theme:end",
  yaml.join("\n"),
  docPath,
);

// Format exactly as lint-staged will, so a commit never rewrites the generated blocks.
const pretty = async (text: string, filepath: string) =>
  format(text, { ...(await resolveConfig(filepath)), filepath });
css = await pretty(css, cssPath);
doc = await pretty(doc, docPath);

if (check) {
  const [oldCss, oldDoc] = await Promise.all([
    readFile(cssPath, "utf8"),
    readFile(docPath, "utf8"),
  ]);
  if (oldCss !== css || oldDoc !== doc) {
    console.error("Theme files are out of date. Run pnpm theme:generate.");
    process.exit(1);
  }
  console.log("Theme files match the generator.");
} else {
  await writeFile(cssPath, css);
  await writeFile(docPath, doc);
  console.log("Wrote both themes to globals.css and DESIGN.md. Every contrast pair passes.");
}
